#!/bin/bash

set -e
set -u

case $# in
  1)  conf="$1" ;;
  *)  echo 1>&2 "Usage: $0 config" ; exit 1 ;;
esac

# load config file
. "$conf"

# sanity check config settings
: "$top $glob $ext"

# process all files
find "$top" -name "$glob.$ext" -print | while read file ; do
  base=$(basename "$file")
  vrt=${file%.$ext}.vrt
  cat <<EOF > "$vrt"
<VRTDataset rasterXSize="720" rasterYSize="360">
  <SRS>GEOGCS[&quot;WGS 84&quot;,DATUM[&quot;WGS_1984&quot;,SPHEROID[&quot;WGS 84&quot;,6378137,298.257223563,AUTHORITY[&quot;EPSG&quot;,&quot;7030&quot;]],TOWGS84[0,0,0,0,0,0,0],AUTHORITY[&quot;EPSG&quot;,&quot;6326&quot;]],PRIMEM[&quot;Greenwich&quot;,0,AUTHORITY[&quot;EPSG&quot;,&quot;8901&quot;]],UNIT[&quot;degree&quot;,0.0174532925199433,AUTHORITY[&quot;EPSG&quot;,&quot;9108&quot;]],AUTHORITY[&quot;EPSG&quot;,&quot;4326&quot;]]</SRS>
  <GeoTransform>  0.0,  0.5,  0.0,  90.0,  0.0, -0.5</GeoTransform>
  <Metadata/>
  <VRTRasterBand dataType="Byte" band="1">
    <Metadata/>
    <ColorInterp>Red</ColorInterp>
    <SimpleSource>
      <SourceFilename relativeToVRT="1">$base</SourceFilename>
      <SourceBand>1</SourceBand>
      <SourceProperties RasterXSize="992" RasterYSize="448" DataType="Byte" BlockXSize="992" BlockYSize="1"/>
      <SrcRect xOff="38" yOff="68" xSize="720" ySize="360"/>
      <DstRect xOff="0" yOff="0" xSize="720" ySize="360"/>
    </SimpleSource>
  </VRTRasterBand>
  <VRTRasterBand dataType="Byte" band="2">
    <Metadata/>
    <ColorInterp>Green</ColorInterp>
    <SimpleSource>
      <SourceFilename relativeToVRT="1">$base</SourceFilename>
      <SourceBand>2</SourceBand>
      <SourceProperties RasterXSize="992" RasterYSize="448" DataType="Byte" BlockXSize="992" BlockYSize="1"/>
      <SrcRect xOff="38" yOff="68" xSize="720" ySize="360"/>
      <DstRect xOff="0" yOff="0" xSize="720" ySize="360"/>
    </SimpleSource>
  </VRTRasterBand>
  <VRTRasterBand dataType="Byte" band="3">
    <Metadata/>
    <ColorInterp>Blue</ColorInterp>
    <SimpleSource>
      <SourceFilename relativeToVRT="1">$base</SourceFilename>
      <SourceBand>3</SourceBand>
      <SourceProperties RasterXSize="992" RasterYSize="448" DataType="Byte" BlockXSize="992" BlockYSize="1"/>
      <SrcRect xOff="38" yOff="68" xSize="720" ySize="360"/>
      <DstRect xOff="0" yOff="0" xSize="720" ySize="360"/>
    </SimpleSource>
  </VRTRasterBand>
</VRTDataset>
EOF
done
